[2023-10-17 13:27:42,741] ERROR     Internal Server Error: /news/add/ /Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/utils/log.py (<class 'smtplib.SMTPDataError'>, SMTPDataError(554, b'5.7.1 Message rejected under suspicion of SPAM; https://ya.cc/1IrBc 1697549262-fRkJOu2BROs0-7C2hf3nJ'), <traceback object at 0x105aeff40>)
Traceback (most recent call last):
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/views/generic/edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/views/generic/edit.py", line 135, in form_valid
    self.object = form.save()
                  ^^^^^^^^^^^
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/forms/models.py", line 543, in save
    self._save_m2m()
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/forms/models.py", line 524, in _save_m2m
    f.save_form_data(self.instance, cleaned_data[f.name])
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/db/models/fields/related.py", line 1956, in save_form_data
    getattr(instance, self.attname).set(data)
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 1236, in set
    self.add(*new_objs, through_defaults=through_defaults)
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 1137, in add
    self._add_items(
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 1447, in _add_items
    signals.m2m_changed.send(
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
           ^
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/news/signals.py", line 53, in notify_managers_appoint
    msg.send()
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/core/mail/message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/core/mail/backends/smtp.py", line 134, in send_messages
    sent = self._send(message)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/core/mail/backends/smtp.py", line 152, in _send
    self.connection.sendmail(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/smtplib.py", line 908, in sendmail
    raise SMTPDataError(code, resp)
smtplib.SMTPDataError: (554, b'5.7.1 Message rejected under suspicion of SPAM; https://ya.cc/1IrBc 1697549262-fRkJOu2BROs0-7C2hf3nJ')
[2023-10-17 13:27:42,745] ERROR     "POST /news/add/ HTTP/1.1" 500 158104 /Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py None
[2023-10-17 13:35:03,365] ERROR     Internal Server Error: /news/add/ /Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/utils/log.py (<class 'smtplib.SMTPDataError'>, SMTPDataError(554, b'5.7.1 Message rejected under suspicion of SPAM; https://ya.cc/1IrBc 1697549703-2Zk3B13BdCg0-JjVMPgKO'), <traceback object at 0x102f79640>)
Traceback (most recent call last):
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/views/generic/edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/views/generic/edit.py", line 153, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/views/generic/edit.py", line 135, in form_valid
    self.object = form.save()
                  ^^^^^^^^^^^
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/forms/models.py", line 543, in save
    self._save_m2m()
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/forms/models.py", line 524, in _save_m2m
    f.save_form_data(self.instance, cleaned_data[f.name])
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/db/models/fields/related.py", line 1956, in save_form_data
    getattr(instance, self.attname).set(data)
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 1236, in set
    self.add(*new_objs, through_defaults=through_defaults)
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 1137, in add
    self._add_items(
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 1447, in _add_items
    signals.m2m_changed.send(
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
           ^
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/news/signals.py", line 53, in notify_managers_appoint
    msg.send()
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/core/mail/message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/core/mail/backends/smtp.py", line 134, in send_messages
    sent = self._send(message)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/core/mail/backends/smtp.py", line 152, in _send
    self.connection.sendmail(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/smtplib.py", line 908, in sendmail
    raise SMTPDataError(code, resp)
smtplib.SMTPDataError: (554, b'5.7.1 Message rejected under suspicion of SPAM; https://ya.cc/1IrBc 1697549703-2Zk3B13BdCg0-JjVMPgKO')
[2023-10-17 13:35:03,368] ERROR     "POST /news/add/ HTTP/1.1" 500 158357 /Users/nikolajmuhamedov/moduleD12_homework_9063/venv/lib/python3.11/site-packages/django/core/servers/basehttp.py None
